# fly.toml app configuration file generated for slack-clone-2616 on 2025-01-13T13:50:30-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'slack-clone-2616'
primary_region = 'bos'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.3'

[env]
  APP_NAME = 'SlackingOff'
  APP_ENV = 'production'
  APP_DEBUG = 'true'
  APP_TIMEZONE = 'UTC'
  APP_URL = 'https://slack-clone-2616.fly.dev'
  ASSET_URL = 'https://slack-clone-2616.fly.dev'
  MEMCACHED_HOST = '127.0.0.1'

  APP_LOCALE = 'en'
  APP_FALLBACK_LOCALE = 'en'
  APP_FAKER_LOCALE = 'en_US'

  APP_MAINTENANCE_DRIVER = 'file'

  PHP_CLI_SERVER_WORKERS = '4'

  BCRYPT_ROUNDS = '12'

  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'debug'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'

  DB_CONNECTION = 'sqlite'

  SESSION_DRIVER = 'database'
  SESSION_LIFETIME = '120'
  SESSION_ENCRYPT = 'false'
  SESSION_PATH = '/'
  SESSION_DOMAIN = 'null'

  BROADCAST_CONNECTION = 'pusher'
  FILESYSTEM_DISK = 's3'
  QUEUE_CONNECTION = 'database'

  CACHE_STORE = 'database'
  CACHE_PREFIX = ''

  MAIL_MAILER = 'log'

  PUSHER_APP_ID = '1925182'
  PUSHER_HOST = 'api-us2.pusher.com'
  PUSHER_PORT = '443'
  PUSHER_SCHEME = 'https'
  PUSHER_APP_CLUSTER = 'us2'

  VITE_APP_NAME = "${APP_NAME}"
  VITE_PUSHER_HOST = "${PUSHER_HOST}"
  VITE_PUSHER_PORT = "${PUSHER_PORT}"
  VITE_PUSHER_SCHEME = "${PUSHER_SCHEME}"
  VITE_PUSHER_APP_CLUSTER = "${PUSHER_APP_CLUSTER}"

  OPENAI_EMBEDDING_MODEL = 'text-embedding-3-small' 

  PINECONE_INDEX = 'slacking-off'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
