# fly.toml app configuration file generated for slack-clone-2616 on 2025-01-13T13:50:30-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'slack-clone-2616'
primary_region = 'bos'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.2'

[env]
  APP_NAME = 'SlackingOff'
  APP_ENV = 'production'
  APP_DEBUG = 'true'
  APP_TIMEZONE = 'UTC'
  APP_URL = 'https://slack-clone-2616.fly.dev'
  ASSET_URL = 'https://slack-clone-2616.fly.dev'
  MEMCACHED_HOST = 'https://slack-clone-2616.fly.dev'

  APP_LOCALE = 'en'
  APP_FALLBACK_LOCALE = 'en'
  APP_FAKER_LOCALE = 'en_US'

  APP_MAINTENANCE_DRIVER = 'file'

  PHP_CLI_SERVER_WORKERS = '4'

  BCRYPT_ROUNDS = '12'

  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'

  DB_CONNECTION = 'sqlite'

  SESSION_DRIVER = 'database'
  SESSION_LIFETIME = '120'
  SESSION_ENCRYPT = 'false'
  SESSION_PATH = '/'
  SESSION_DOMAIN = 'null'

  BROADCAST_CONNECTION = 'reverb'
  FILESYSTEM_DISK = 'local'
  QUEUE_CONNECTION = 'database'

  CACHE_STORE = 'database'
  CACHE_PREFIX = ''

  MAIL_MAILER = 'log'

  VITE_APP_NAME = 'SlackingOff'

  REVERB_APP_ID = '758030'
  REVERB_APP_KEY = 'q3g1wcsq7lgoorqs6hsv'
  REVERB_HOST = 'https://slack-clone-2616.fly.dev'
  REVERB_PORT = '8080'
  REVERB_SCHEME = 'http'

  VITE_REVERB_APP_KEY = 'q3g1wcsq7lgoorqs6hsv'
  VITE_REVERB_HOST = 'https://slack-clone-2616.fly.dev'
  VITE_REVERB_PORT = '8080'
  VITE_REVERB_SCHEME = 'http'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
